from enum import Enum
class ReasoningMode(Enum): DEDUCTIVE = 'DEDUCTIVE'; INDUCTIVE = 'INDUCTIVE'; ABDUCTIVE = 'ABDUCTIVE'
class NodeType(Enum): FACT = 'FACT'; HYPOTHESIS = 'HYPOTHESIS'; RULE = 'RULE'; CLAIM = 'CLAIM'
class RelationType(Enum): DERIVED_FROM = 'DERIVED_FROM'; CONTRADICTS = 'CONTRADICTS'; CAUSES = 'CAUSES'; CORRELATES_WITH = 'CORRELATES_WITH'; SUPPORTS = 'SUPPORTS'
