class AIReasoningArchitecturalError(Exception): pass
class QuarantineBypassError(AIReasoningArchitecturalError): pass
class HypothesisIsolationError(AIReasoningArchitecturalError): pass
class ConfidenceInflationError(AIReasoningArchitecturalError): pass
class SilentMutationError(AIReasoningArchitecturalError): pass
class SafetyViolationError(AIReasoningArchitecturalError): pass
