name: Docker Image Build Test

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Compose Stack
      run: docker-compose build
